# Practical Exercise: Exploring an Agricultural Knowledge Base with Python

## Objective
In this practical, you will use a small agricultural question-and-answer dataset to understand the basic idea of **retrieval**.

You will:

1. Load the Excel dataset.
2. Keep only the English questions and answers.
3. Explore a few examples.
4. Type a new agricultural question.
5. Ask Python to find the most similar question in the knowledge base.
6. Retrieve the corresponding answer.
7. Experiment with different ways of asking the same question.

### Key idea

**Your question → Search the knowledge base → Find relevant information → Return an answer**

This is a simplified demonstration of the **retrieval** part of Retrieval-Augmented Generation (RAG).

> You are **not training an AI model** in this exercise.

## Step 1 — Import the required Python libraries

We will use:

- `pandas` to read the Excel file
- `scikit-learn` to compare questions

In [ ]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries loaded successfully.")

Libraries loaded successfully.

## Step 2 — Load the dataset

Make sure the Excel file **Mkulima Knowledge Base_SwEN(1).xlsx** is in the same folder as this notebook.

Run the cell below.

In [ ]:
file_name = "/content/Mkulima Knowledge_Base.xlsx"

df = pd.read_excel(file_name)

print("Dataset loaded successfully.")
print("Number of rows:", len(df))

df.head()

Dataset loaded successfully.
Number of rows: 174

,Maswali,Qestions,Majibu,Unnamed: 3,Unnamed: 4,Answers
0,Jinsi gani upepo unavyosababisha mmomonyoko wa...,How does wind cause soil erosion and affect co...,Upepo huondoa safu ya juu ya udongo na kupelek...,NaN,NaN,Wind removes the top layer of soil and affects...
1,Umuhimu wa uchavushaji kwa mmea wa mahindi ni ...,What is the importance of pollination for corn...,Uchavushaji husaidia mmea kuweza kuzalisha tun...,NaN,NaN,Pollination helps the plant to produce fruit. ...
2,Yapi kati ya Mahindi yaliyokauka na mahindi ma...,What are the differences between dried and fre...,Bei ya mahindi mabichi au makavu hutegemea sok...,NaN,NaN,The price of fresh or dry corn depends on the ...
3,Mmea wa mahindi una aina gani ya mizizi?,What type of root system does a corn plant have?,Mmea wa mahindi huwa na aina ya mizizi miemaba...,NaN,NaN,"Corn plants have a type of thin, fibrous roots..."
4,Jinsi gani naweza kuoboresha virutubisho kati...,How can I improve the nutrients in corn plants?,Kuna namna mbalimbali za kuboresha virutisho k...,NaN,NaN,There are various ways to improve nutrients in...

## Step 3 — Keep only the English questions and answers

The original dataset contains both Swahili and English.

For this exercise, we will use:

- `Qestions` = English questions
- `Answers` = English answers

We will rename them to make the dataset easier to read.

In [ ]:
data = df[["Qestions", "Answers"]].copy()

data.columns = ["Question", "Answer"]

data = data.dropna()

print("Number of English question-answer pairs:", len(data))

data.head()

Number of English question-answer pairs: 172

,Question,Answer
0,How does wind cause soil erosion and affect co...,Wind removes the top layer of soil and affects...
1,What is the importance of pollination for corn...,Pollination helps the plant to produce fruit. ...
2,What are the differences between dried and fre...,The price of fresh or dry corn depends on the ...
3,What type of root system does a corn plant have?,"Corn plants have a type of thin, fibrous roots..."
4,How can I improve the nutrients in corn plants?,There are various ways to improve nutrients in...

## Step 4 — Look at a few examples

Run the cell below to see five random question-and-answer pairs from the agricultural knowledge base.

Run it more than once and observe how the examples change.

In [ ]:
data.sample(5)

,Question,Answer
54,At what stage of corn growth should I apply fe...,"When preparing the field, it's advised to mix ..."
14,How does temperature aid in corn seed germinat...,"For a seed to grow, it needs a warm temperatur..."
133,Why do some corn plants grow tall but do not p...,Lack of sufficient sunlight in the field.
9,Does the presence of holes in the seeds hinder...,"Yes, pests that bore into corn eat the core of..."
15,How many diseases affect corn?,Corn is affected by many diseases. These disea...

## Step 5 — Prepare the questions for searching

We will use a simple method called **TF-IDF**.

You do not need to understand the mathematics for this exercise.

The important idea is:

> Python converts the questions into a form that allows it to compare how similar their words are.

In [ ]:
questions = data["Question"].fillna("")

vectorizer = TfidfVectorizer(stop_words="english")

question_vectors = vectorizer.fit_transform(questions)

print("The knowledge base is ready for searching.")

The knowledge base is ready for searching.

## Step 6 — Create a simple search function

The function below will:

1. Take your question.
2. Compare it with all questions in the knowledge base.
3. Find the closest question.
4. Return its answer.

Run the cell once to create the function.

In [ ]:
def search_knowledge_base(user_question):

    user_vector = vectorizer.transform([user_question])

    similarities = cosine_similarity(
        user_vector,
        question_vectors
    )[0]

    best_match = similarities.argmax()

    matched_question = data.iloc[best_match]["Question"]
    matched_answer = data.iloc[best_match]["Answer"]
    score = similarities[best_match]

    print("YOUR QUESTION")
    print(user_question)

    print("\nCLOSEST QUESTION IN THE KNOWLEDGE BASE")
    print(matched_question)

    print("\nRETRIEVED ANSWER")
    print(matched_answer)

    print("\nSIMILARITY SCORE")
    print(round(score, 3))

## Step 7 — Try your first question

Run the example below.

In [ ]:
search_knowledge_base(
    "Why are my maize seeds not germinating?"
)

YOUR QUESTION
Why are my maize seeds not germinating?

CLOSEST QUESTION IN THE KNOWLEDGE BASE
Should I use native seeds for planting after using improved seeds in the previous season?

RETRIEVED ANSWER
No. For proper yields and productive farming, it's recommended to use improved seed varieties every season.

SIMILARITY SCORE
0.476

## Step 8 — Your turn

Change the question inside the quotation marks and run the cell again.

Try questions such as:

- How can I protect maize from pests?
- Why are my maize plants turning yellow?
- How should I store maize after harvest?
- What causes poor maize growth?

You can also write your own question.

In [ ]:
my_question = "How should I store maize after harvest?"

search_knowledge_base(my_question)

YOUR QUESTION
How should I store maize after harvest?

CLOSEST QUESTION IN THE KNOWLEDGE BASE
How long does it take for corn to reach harvest time?

RETRIEVED ANSWER
Maize takes from 90 to 140 days.

SIMILARITY SCORE
0.383

## Step 9 — Ask the same question in different ways

Now test whether changing the wording changes the result.

Run each example below one at a time.

In [ ]:
search_knowledge_base(
    "Why are my maize seeds not germinating?"
)

YOUR QUESTION
Why are my maize seeds not germinating?

CLOSEST QUESTION IN THE KNOWLEDGE BASE
Should I use native seeds for planting after using improved seeds in the previous season?

RETRIEVED ANSWER
No. For proper yields and productive farming, it's recommended to use improved seed varieties every season.

SIMILARITY SCORE
0.476

In [ ]:
search_knowledge_base(
    "What prevents maize seeds from sprouting?"
)

YOUR QUESTION
What prevents maize seeds from sprouting?

CLOSEST QUESTION IN THE KNOWLEDGE BASE
Should I use native seeds for planting after using improved seeds in the previous season?

RETRIEVED ANSWER
No. For proper yields and productive farming, it's recommended to use improved seed varieties every season.

SIMILARITY SCORE
0.476

In [ ]:
search_knowledge_base(
    "Why did my corn seeds fail to grow?"
)

YOUR QUESTION
Why did my corn seeds fail to grow?

CLOSEST QUESTION IN THE KNOWLEDGE BASE
What causes corn seeds to fail to germinate?

RETRIEVED ANSWER
The condition of corn seeds not germinating even if the conditions suitable for seedling growth are available is caused by a certain type and the embryo is not yet mature when it germinates. The presence of environmental barriers including excess moisture, oxygen, light, and suitable temperature, but also the seeds being placed in conditions that are not suitable for germination.

SIMILARITY SCORE
0.612

## Discussion

Discuss the following questions with your group:

1. Did the three differently worded questions retrieve the same information?
2. Which question produced the best match?
3. What happened when you used words that were very different from those in the dataset?
4. What are the limitations of this simple word-based search method?
5. Why might a trusted agricultural knowledge base be useful when building an AI advisory system?

### Connection to RAG

In this exercise, we only performed retrieval:

**Question → Search → Retrieve information**

In a full RAG system, the retrieved information would then be given to a language model:

**Question → Search → Retrieve information → LLM → Final answer**

In [ ]:
from sentence_transformers import CrossEncoder

# 1. Load the E5 Embedding Model
# E5 models are highly effective for multilingual tasks
model_e5 = SentenceTransformer('intfloat/multilingual-e5-base')

# 2. Load the BGE Reranker
# This model compares the query and document directly to give a precise relevance score
reranker = CrossEncoder('BAAI/bge-reranker-v2-m3')

# 3. Prepare Knowledge Base with E5 prefixes
# E5 requires 'passage: ' prefix for the documents it indexes
kb_passages = [f"passage: {q}" for q in kb_questions]
kb_embeddings_e5 = model_e5.encode(kb_passages, convert_to_tensor=True)

def advanced_search(query, top_k_retrieval=5):
    # E5 requires 'query: ' prefix for the search term
    query_prefixed = f"query: {query}"
    query_embedding = model_e5.encode(query_prefixed, convert_to_tensor=True)

    # Initial Retrieval (Top 5 candidates)
    hits = util.semantic_search(query_embedding, kb_embeddings_e5, top_k=top_k_retrieval)[0]

    # Prepare pairs for Reranking
    sentence_pairs = [[query, data.iloc[hit['corpus_id']]['Question']] for hit in hits]

    # Get Reranker Scores
    rerank_scores = reranker.predict(sentence_pairs)

    # Find the best after reranking
    best_hit_idx = rerank_scores.argmax()
    best_corpus_id = hits[best_hit_idx]['corpus_id']
    final_score = rerank_scores[best_hit_idx]

    return data.iloc[best_corpus_id]['Question'], data.iloc[best_corpus_id]['Answer'], final_score

# Test with your queries
advanced_results = []
for q in test_queries:
    match_q, match_a, score = advanced_search(q)
    advanced_results.append({
        'User Query': q,
        'E5+BGE Match': match_q,
        'Reranker Score': round(float(score), 4)
    })

advanced_df = pd.DataFrame(advanced_results)
display(advanced_df)

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/179k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.11GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

,User Query,E5+BGE Match,Reranker Score
0,Why are my maize seeds not germinating?,What leads to poor germination of my corn seeds?,0.8369
1,What stops corn from sprouting?,What causes corn seeds to fail to germinate?,0.9019
2,Ways to keep corn safe from bugs.,How can I manage damaging insects in my corn garden?,0.9105

In [ ]:
final_comparison_data = []

for q in test_queries:
    # 1. TF-IDF Score
    _, _, s_tfidf = tfidf_search(q)
    # 2. MiniLM Score
    _, _, s_minilm = semantic_search(q)
    # 3. MPNet Score
    _, s_mpnet = semantic_search_large(q)
    # 4. Multi-QA (Dot) Score
    _, s_qa = semantic_search_qa(q)
    # 5. E5+BGE Reranker Score
    _, _, s_rerank = advanced_search(q)

    final_comparison_data.append({
        'User Query': q,
        'TF-IDF': round(float(s_tfidf), 3),
        'MiniLM': round(float(s_minilm), 3),
        'MPNet': round(float(s_mpnet), 3),
        'Multi-QA (Dot)': round(float(s_qa), 3),
        'E5+BGE (Rerank)': round(float(s_rerank), 3)
    })

master_comparison_df = pd.DataFrame(final_comparison_data)
display(master_comparison_df)

print("\nNOTE: Multi-QA uses 'Dot Product' (unbounded), while others use Cosine or Reranker scales (usually 0 to 1).")

,User Query,TF-IDF,MiniLM,MPNet,Multi-QA (Dot),E5+BGE (Rerank)
0,Why are my maize seeds not germinating?,0.476,0.839,0.789,27.342,0.837
1,What stops corn from sprouting?,0.294,0.738,0.839,26.101,0.902
2,Ways to keep corn safe from bugs.,0.569,0.789,0.769,29.187,0.910

NOTE: Multi-QA uses 'Dot Product' (unbounded), while others use Cosine or Reranker scales (usually 0 to 1).

### Step 10 — The Generation Stage (Completing the RAG)

Instead of an API-based model, we can use an open-source model like **Qwen 2.5 3B**. This model is highly capable and small enough to run on a Colab GPU using quantization.

In [ ]:
!pip install -q -U transformers accelerate bitsandbytes

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

# 1. Load Qwen 2.5 3B Instruct in 4-bit to save memory
model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model_qwen = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    quantization_config=None, # For T4 GPU, we rely on high-performance loading
    torch_dtype=torch.bfloat16
)

qwen_pipeline = pipeline(
    "text-generation",
    model=model_qwen,
    tokenizer=tokenizer,
)

def generate_qwen_rag_response(user_query):
    # A. Retrieval Stage
    matched_q, matched_a, score = advanced_search(user_query)

    # B. Generation Stage for Qwen
    messages = [
        {"role": "system", "content": "You are an expert Agricultural Advisor. Use the provided context to answer the farmer's question politely."},
        {"role": "user", "content": f"Question: {user_query}\nContext: {matched_a}"}
    ]

    # Format the prompt using Qwen's template
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    outputs = qwen_pipeline(
        text,
        max_new_tokens=256,
        do_sample=True,
        temperature=0.7,
        top_p=0.9
    )

    response_text = outputs[0]["generated_text"][len(text):]

    print(f"--- QWEN RAG SYSTEM OUTPUT ---")
    print(f"USER QUERY: {user_query}")
    print(f"RETRIEVED FACT: {matched_a}")
    print(f"\nFINAL ADVISORY:\n{response_text}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 17.0 MB/s eta 0:00:00

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
# Test the Qwen-powered RAG
generate_qwen_rag_response("How can I improve the nutrients in corn plants?")

[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'temperature', 'max_new_tokens', 'top_p'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

--- QWEN RAG SYSTEM OUTPUT ---
USER QUERY: How can I improve the nutrients in corn plants?
RETRIEVED FACT: There are various ways to improve nutrients in corn. One way is to make sure that the plant is well-fertilized when it is in the field and is given the nutrients it needs to grow and produce corn. Another way involves the care of corn in a dry and clean condition when the corn is ripe and ready for milling to make food. Sometimes it is advisable to add nutritional supplements to the flour made after grinding corn.

FINAL ADVISORY:
To improve the nutrient content in corn plants, you should ensure they are properly fertilized with essential nutrients while growing in the field. This helps them develop strong and healthy crops. Additionally, after harvesting, maintaining a dry and clean storage environment for the corn can help preserve its nutritional value. If needed, adding nutritional supplements to the ground corn flour produced from milling the corn can also enhance its nutrient profile.

### Step 12 — Deploying the Agricultural Advisor Website

We will now use **Gradio** to build the user interface. This creates a text box for the farmer and separate output boxes for the database retrieval and the AI's final advice.

In [ ]:
import gradio as gr
import torch
from transformers import pipeline
import scipy.io.wavfile as wavfile
import numpy as np

# 1. Initialize the TTS Pipeline
tts_pipe = pipeline("text-to-speech", model="facebook/mms-tts-eng", device="cuda" if torch.cuda.is_available() else "cpu")

def rag_website_interface(user_query):
    # A. Retrieval Stage
    matched_q, matched_a, score = advanced_search(user_query)

    # B. Generation Stage (Qwen)
    messages = [
        {"role": "system", "content": "You are an expert Agricultural Advisor. Use the provided context to answer the farmer's question politely."},
        {"role": "user", "content": f"Question: {user_query}\nContext: {matched_a}"}
    ]

    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    outputs = qwen_pipeline(text, max_new_tokens=256, do_sample=True, temperature=0.7, top_p=0.9)
    response_text = outputs[0]["generated_text"][len(text):]

    # C. TTS Stage
    speech = tts_pipe(response_text)
    # Gradio audio expects (sample_rate, numpy_array)
    audio_output = (speech["sampling_rate"], speech["audio"].squeeze())

    return matched_a, response_text, audio_output

# Define the Updated Web UI
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🌽 Mkulima AI: Agricultural Knowledge Assistant (with Audio)")
    gr.Markdown("Ask any question about maize farming to receive text and audio advice.")

    with gr.Row():
        with gr.Column():
            query_input = gr.Textbox(label="Your Question", placeholder="e.g., How do I protect corn from pests?")
            submit_btn = gr.Button("Ask Assistant", variant="primary")

    with gr.Row():
        with gr.Column():
            retrieval_output = gr.Textbox(label="Step 1: Retrieved Fact (from Database)", interactive=False)
        with gr.Column():
            advisory_output = gr.Textbox(label="Step 2: AI Final Advisory", interactive=False)
            audio_output = gr.Audio(label="Listen to Advisory", type="numpy")

    submit_btn.click(fn=rag_website_interface, inputs=query_input, outputs=[retrieval_output, advisory_output, audio_output])

# Launch the app
demo.launch(share=True, debug=False)

config.json:   0%|          | 0.00/1.64k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  145MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/762 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/287 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/413 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/47.0 [00:00<?, ?B/s]

/tmp/ipykernel_3107/3384949697.py:32: UserWarning: The parameters have been moved from the Blocks constructor to the launch() method in Gradio 6.0: theme. Please pass these parameters to launch() instead.
  with gr.Blocks(theme=gr.themes.Soft()) as demo:

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://87ffd11941525cac04.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)